default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ecruzcontrol_development

test:
  <<: *default
  database: ecruzcontrol_test

production:
  <<: *default
  database: ecruzcontrol_production
